# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: utils
    init: |
      docker pull efrecon/mqtt-client
      echo -e "\033[1;44mSome useful commands\033[0m"
      echo -e "\033[1;32mNode.js\033[0m"
      node -e "console.log(require('os').version())"
      echo -e "\033[1;33mGitpod\033[0m"
      (gp ports list 2> /dev/null) || true
      gp info
      gp top
      echo -e "\033[1;31mMySQL\033[0m"
      echo -e "\033[0;32mGenerate hash for access token\033[0m"
      node -e "console.log(require('crypto').createHash('sha3-256').update('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx').digest('hex'))"
      echo -e "\033[0;32mmMySQL dump and restore\033[0m"
      echo "docker exec db-mysql /usr/bin/mysqldump --databases -u root --password=secret idm > backup.sql"
      echo "cat backup.sql | docker exec -i db-mysql /usr/bin/mysql -u root --password=secret idm"
      echo -e "\033[1;34mMQTT\033[0m"
      docker run -it --rm --name mqtt-sub --network fiware_default efrecon/mqtt-client sub -h mqtt -t "telegraf/#"
      docker run -it --rm --name mqtt-pub --network fiware_default efrecon/mqtt-client pub -h mqtt -m '{"id":"TT001","temperature":24}' -t "telegraf/sensor/01"
      echo -e "\033[1;36mDocker\033[0m"
      docker exec -it db-mysql /bin/bash
      docker compose -p fiware logs fiware-orion -f
      docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
  - name: build
    init: docker compose pull # runs during prebuild
    command: |
      sudo chown -R 472:472 grafana/.db
      sudo chown -R 1000:1000 node-red/data
      echo Welcome to FIWARE
      docker compose -p fiware down -v --remove-orphans
      docker compose -p fiware up -d --remove-orphans --build
      echo Waking up FIWARE Node-RED app on Replit...
      curl https://fiware.zeldalegends.repl.co/gitpod -d url=$(node -e "console.log(require('process').env.GITPOD_WORKSPACE_URL)")

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - description: JSON LD @context files
    port: 80
    onOpen: ignore
  - description: Orion Context Broker
    port: 1026
    onOpen: notify
  - description: Wilma PEP Proxy (Orion)
    port: 1027
    onOpen: ignore
    visibility: public
  - description: Orion-LD Context Broker
    port: 1028
    onOpen: notify
  - description: Wilma PEP Proxy (Orion-LD)
    port: 1029
    onOpen: ignore
    visibility: public
  - description: Node-RED
    port: 1880
    onOpen: notify
  - name: 
    description: Wilma PEP Proxy (Node-RED)
    port: 1881
    onOpen: ignore
    visibility: public
  - description: Mosquitto MQTT Broker
    port: 1883
    onOpen: ignore
    visibility: public
  - description: MQTT over Websocket
    port: 9001
    onOpen: ignore
    visibility: public
#  - description: Tutorial App context data
#    port: 3000
#    onOpen: open-preview
#    visibility: public
#  - description: Tutorial Devices over HTTP
#    port: 3001
#    onOpen: ignore
  - description: Keyrock Identity Manager
    port: 3005
    onOpen: open-preview
    visibility: public
  - description: MySQL Database
    port: 3306
    onOpen: ignore
  - description: IoT Agent (North Port)
    port: 4041
    onOpen: ignore
  - description: IoT Agent (South Port)
    port: 7896
    onOpen: ignore
  - description: Simple Express application
    port: 8000
    onOpen: notify
  - description: Wilma PEP Proxy (Express App)
    port: 8001
    onOpen: ignore
    visibility: public
#  - description: Simple web application
#    port: 8082
#    onOpen: notify
#  - description: Wilma PEP Proxy (Web App)
#    port: 8083
#    onOpen: ignore
#    visibility: public
  - description: MongoExpress
    port: 8081
    onOpen: ignore
    visibility: public
  - description: MongoDB
    port: 27017
    onOpen: ignore
  - description: Grafana
    port: 3000
    onOpen: ignore
    visibility: public
  - description: InfluxDB
    port: 8086
    onOpen: ignore
    visibility: public
  - description: Ganache Truffle private chain
    port: 7545
    onOpen: ignore
    visibility: public