services:
  orion:
    image: fiware/orion:3.0.0
    hostname: orion
    ports:
      - "1026:1026" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG

  orion-ld:
    image: fiware/orion-ld:1.1.0
    hostname: orion-ld
    ports:
      - "1028:1026" # localhost:1028
    command: -dbhost mongo-db -db orionld -logLevel DEBUG

  keyrock:
    image: fiware/idm:8.1.0-distroless
    hostname: keyrock
    ports:
      - "3005:3005" # localhost:3005
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_DB_PASS=secret
      - IDM_DB_USER=root
      - IDM_HOST=http://localhost:3005
      - IDM_PORT=3005
      - IDM_HTTPS_ENABLED=false
      - IDM_HTTPS_PORT=3443
      - IDM_ADMIN_USER=alice
      - IDM_ADMIN_EMAIL=alice-the-admin@test.com
      - IDM_ADMIN_PASS=test

  orion-proxy:
    image: fiware/pep-proxy:8.1.0-distroless
    hostname: orion-proxy
    ports:
      - "1027:1027" # localhost:1027
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_APP_HOST=orion
      - PEP_PROXY_APP_PORT=1026
      - PEP_PROXY_PORT=1027
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
      - PEP_PASSWORD=test
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/version

  orion-ld-proxy:
    image: fiware/pep-proxy:8.1.0-distroless
    hostname: orion-ld-proxy
    ports:
      - "1029:1029" # localhost:1029
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_APP_HOST=orion-ld
      - PEP_PROXY_APP_PORT=1026
      - PEP_PROXY_PORT=1029
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
      - PEP_PASSWORD=test
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/version

  web-app:
    image: node:16-alpine
    hostname: web-app
    ports:
      - "8082:8082" # localhost:8002
    command: node -e \
      "var http=require('http');
       var parser=require('querystring');
       http.createServer(function(req, res) {
         if (req.url.startsWith('/test?')) {
           var test = parser.parse(req.url.replace('/test?', ''));
           if (test.t > 75) test._result = 'Possible short-circuit or spark-gap in device ' + test.d + '.';
           if (test.t < 25) test._result = 'Is device ' + test.d + ' shut down?';
           res.write(JSON.stringify(test));
         } else {
           if (req.url.startsWith('/v'))
             res.write('1.0.0, by Alerox 2022.');
           else
             res.write('<html>' +
               '<h1>Simple ADS</h1>' +
               '<h3>by Alerox, 2022</h3>' +
               'Usage <code>/test?d=device&t=temperature</code></html>');
         }
         res.end();
       }).listen(8082);
       console.log('USEFUL COMMANDS');
       console.log('cat backup.sql | docker exec -i db-mysql /usr/bin/mysql -u root --password=secret idm');
       console.log('docker exec db-mysql /usr/bin/mysqldump --databases -u root --password=secret idm > backup.sql');
       console.log('(gp ports list 2> /dev/null) || true');
       console.log('docker ps --format \'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\'');
       console.log();
       console.log(`Server started on port 8082`);"
  
  web-app-proxy:
    image: fiware/pep-proxy:8.1.0-distroless
    hostname: web-app-proxy
    ports:
      - "8083:8083" # localhost:8003
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_APP_HOST=web-app
      - PEP_PROXY_APP_PORT=8082
      - PEP_PROXY_PORT=8083
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
      - PEP_PASSWORD=test
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/version

  node-red:
    image: nodered/node-red
    hostname: node-red
    ports:
      - "1880:1880" # localhost:1880

  node-red-proxy:
    image: fiware/pep-proxy:8.1.0-distroless
    hostname: node-red-proxy
    ports:
      - "1881:1881" # localhost:1881
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_APP_HOST=node-red
      - PEP_PROXY_APP_PORT=1880
      - PEP_PROXY_PORT=1881
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
      - PEP_PASSWORD=test
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/version

  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    ports:
      - "27017:27017" # localhost:27017
    command: --nojournal
    
  mongo-express:
    image: mongo-express:1.0.0-alpha
    hostname: mongo-express
    ports:
      - "8081:8081" # localhost:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db

  mysql-db:
    image: mysql:5.7
    hostname: mysql-db
    ports:
      - "3306:3306" # localhost:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=%" # Allow any container to access this database
